### ISSUE TITLE
Thank you!

### ISSUE THREAD

**Issue by ptrkstr** [cltnschlosser/IntegratedDriverDuplicateFilenames#1]
When googling `"error: Unexpected error in driver invocation: fatalError"`, your repo was the only one that came up and solved my issue exactly. Thank you immensely for sharing this find @cltnschlosser. Can I ask how you came across this?

**Comment by cltnschlosser** [comment]
I found the issue when using the new beta `EnableSwiftBuildSystemIntegration` flag. I have some experience with swift-driver, so I knew that was likely where the error was coming from. The specific error is a swift-driver thrown error not being handled properly in xcode. I created this repo as a test case for Apple engineers when I filed my radar/feedback. My feedback is marked as potential fix identified - for a future update, so should be fixed soon in a future xcode version 😄 

I specifically hit this issue when having multiple swift files with the same name (as shown in this repo), but I think other errors could potentially give you the fatalError output as well.
